function [tagType,args] = stimulateParameterToOsc(stimulateParameter)
    tagType = 'BiBiiiiiiiiiii';
    args = {stimulateParameter.chBiphasic,stimulateParameter.chBurstPulseCount,stimulateParameter.chEnable,...
            stimulateParameter.chInterBurstInterval,stimulateParameter.chInterPhaseCurrent,stimulateParameter.chInterPhaseInterval,...
            stimulateParameter.chInterPulseInterval,stimulateParameter.chPhaseOneCurrent,stimulateParameter.chPhaseOneDuration,...
            stimulateParameter.chPhaseTwoCurrent,stimulateParameter.chPhaseTwoDuration,stimulateParameter.chStimulateChannel,...
            stimulateParameter.chTrainBurstCount,stimulateParameter.chTriggerDelay};
end